# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-22 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='expired',
        ),
    ]
